enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[Instagram]
apkmirror-dlurl = "https://www.apkmirror.com/apk/instagram/instagram-instagram/"
arch = "arm64-v8a"
build-mode = "both"

[Tiktok]
apkmirror-dlurl = "https://www.apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly/"
arch = "arm64-v8a"
build-mode = "both"

[X]
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter/"
arch = "arm64-v8a"
build-mode = "both"
included-patches = "'Hide view count'"

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
arch = "arm64-v8a"
build-mode = "both"
included-patches = "'Enable slide to seek'"

[FaceBook]
apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-2/facebook/"
arch = "arm64-v8a"
build-mode = "both"

[com.spotify.music]
apkmirror-dlurl = "https://www.apkmirror.com/apk/spotify-ltd/spotify-music-and-podcasts-amazon-fire-tablet-version/"
arch = "arm64-v8a"
build-mode = "both"


